package daddy.gui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;

/**
 * Displays one chat message with a blank avatar placeholder.
 */
public class DialogBox extends HBox {
    /** Limits the width of a message bubble so long text remains readable. */
    private static final double MAX_BUBBLE_WIDTH = 440.0;

    /**
     * Creates a chat message aligned for either the user or Daddy.
     *
     * @param text the message displayed in the bubble
     * @param isUser whether the message belongs to the user
     */
    private DialogBox(String text, boolean isUser) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(MAX_BUBBLE_WIDTH);
        message.getStyleClass().add("message-bubble");

        Region avatarPlaceholder = new Region();
        avatarPlaceholder.getStyleClass().addAll("avatar-placeholder", isUser ? "user-avatar" : "daddy-avatar");

        setSpacing(10.0);
        getStyleClass().add(isUser ? "user-dialog" : "daddy-dialog");
        if (isUser) {
            setAlignment(Pos.TOP_RIGHT);
            getChildren().addAll(message, avatarPlaceholder);
        } else {
            setAlignment(Pos.TOP_LEFT);
            getChildren().addAll(avatarPlaceholder, message);
        }
    }

    /**
     * Creates a dialog box for a command entered by the user.
     *
     * @param text the user-entered command
     * @return a right-aligned user dialog box
     */
    public static DialogBox forUser(String text) {
        return new DialogBox(text, true);
    }

    /**
     * Creates a dialog box for Daddy's response.
     *
     * @param text the response generated by Daddy
     * @return a left-aligned Daddy dialog box
     */
    public static DialogBox forDaddy(String text) {
        return new DialogBox(text, false);
    }
}
